@host = http://localhost:3000
@prefix = api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNTlhYzFkOS1iMDZhLTRhNTQtOGRiMy1iMzYxMzM3NTQ4MGQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTI0MzQwMDgsImV4cCI6MTc1MjQzNzYwOH0.f5kXgyMJ3iItiFkMKSn2imMf3lbrO8bxtXeqY2mj4_Q


### Listar Ingreso y salida
GET {{host}}/{{prefix}}/inventory-documents?page=1&limit=5
Authorization: Bearer {{token}}