@host = http://localhost:3000
@prefix = api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YTMyZjIxMi0zNmZkLTRmZmYtYmY0ZC01Y2VhMDk2ZjhiNDIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTE5NDkxNDksImV4cCI6MTc1MTk1Mjc0OX0.ym3NnPB701-SVAM5_lzLsbCRUMVjnyWyPCMIG_teEdI


### Crear producto (ADMIN/VENDOR)
POST {{host}}/{{prefix}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "sku": "PROD-020",
  "name": "Llave de carraca 1/2\"",
  "description": "Llave de carraca con mango antideslizante.",
  "price": 22.50
}


### Crear un registro de inventario
POST http://localhost:3000/api/v1/inventory
Content-Type: application/json

{
  "productId": "5f28fc6f-48cb-4463-9bbe-dde671485d7d",
  "quantity": 100,
  "status": "available"
}


### Listar todos los productos (con token)
GET {{host}}/{{prefix}}/products
Authorization: Bearer {{token}}



### Listar todos los inventarios
GET http://localhost:3000/api/v1/inventory
