@host = http://localhost:3000
@prefix = api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YTMyZjIxMi0zNmZkLTRmZmYtYmY0ZC01Y2VhMDk2ZjhiNDIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTIxMjI2ODcsImV4cCI6MTc1MjEyNjI4N30.qhxCx_dtxL6kZfz5D26_yI-KmWA3RLiT6wNmM48dDCs
@id  = 3ffaa8fa-04cc-4c74-b96d-77c3b38819ad

### Crear un registro de inventario
POST {{host}}/{{prefix}}/inventory
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productId": "6d3fe168-ab5b-47e9-b522-fbc9456e16b3",
  "quantity": 5,
  "status": "available"
}

### Listar todos los inventarios
GET {{host}}/{{prefix}}/inventory/
Authorization: Bearer {{token}}

### Obtener un ítem por ID
GET {{host}}/{{prefix}}/inventory/{{id}}
Authorization: Bearer {{token}}

### Actualizar un ítem
PATCH {{host}}/{{prefix}}/inventory/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "quantity": 501
}

### Eliminar un ítem
DELETE {{host}}/{{prefix}}/inventory/{{id}}
Authorization: Bearer {{token}}



### Opción  semántica: entrada +20
PATCH {{host}}/{{prefix}}/inventory/{{id}}/in
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "delta": 500
}

### Opción semántica: salida  –20
PATCH {{host}}/{{prefix}}/inventory/{{id}}/out
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "delta": 2
}


### Listar stock bajo (umbral 5)
GET {{host}}/{{prefix}}/inventory/reports/low-stock?threshold=5
Authorization: Bearer {{token}}



### Buscar por nombre de producto “Martillo”
GET {{host}}/{{prefix}}/inventory/product/search?productName=Martillo
Authorization: Bearer {{token}}

### Buscar por estado
GET {{host}}/{{prefix}}/inventory/product/search?status=reserved
Authorization: Bearer {{token}}

### Buscar por nombre y estado
GET {{host}}/{{prefix}}/inventory/product/search?productName=martillo&status=available
Authorization: Bearer {{token}}

### Búsqueda sin filtros (devuelve todo)
GET {{host}}/{{prefix}}/inventory/product/search
Authorization: Bearer {{token}}

