@host = http://localhost:3000
@prefix = api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMmVhOTJiYy0zZGJkLTRmMmQtYjY4ZS05MmNkNTU2MjIxMGYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTIxNzU0NzQsImV4cCI6MTc1MjE3OTA3NH0.gEzdvO0t53zZwNRsIQXmhdvWZDea2WsZRjJSXq2nVpk


### LISTAR TODOS LOS PRODUCTOS (CON TOKEN)
GET {{host}}/{{prefix}}/products
Authorization: Bearer {{token}}


### LISTAR PRODUCTO POR ID
GET {{host}}/{{prefix}}/products/fdfa0192-4586-4e0b-b2e7-90d2df6db087
Authorization: Bearer {{token}}


### CREAR PRODUCTO (ADMIN/VENDOR)
POST {{host}}/{{prefix}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "sku": "PROD-7",
  "name": "Llave de carraca 1/2\"",
  "description": "Llave de carraca con mango antideslizante.",
  "price": 22.50
}

### UPDATE PRODUCTO (ADMIN/VENDOR)
PATCH {{host}}/{{prefix}}/products/c5e5fb58-7a51-4f40-8254-6e2383e6a9b1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "sku": "PROD-0211",
  "name": "Llave de carraca 1/2\"",
  "description": "Llave de carraca con mango antideslizante.",
  "price": 50.50
}


### ELIMINAR
DELETE {{host}}/{{prefix}}/products/051f1fcf-3657-4275-ba2a-723447adc27a
Authorization: Bearer {{token}}
