@host = http://localhost:3000
@prefix = api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMmM0ZjYwZS05OTJlLTQ4YjctODczYi00M2QwZGM1MjE2OGUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTIyNjU5MDQsImV4cCI6MTc1MjI2OTUwNH0.Jt1qh8tejFHguCzk8pksbV0caQ9z0Qx_9b_Sc1uvhIU


### CREAR PRODUCTO (ADMIN/VENDOR)
POST {{host}}/{{prefix}}/product-types
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Herramientas",
  "description": "Productos de ferretería"
}


### LISTAR TODOS TIPOS DE PRODUCTOS
GET {{host}}/{{prefix}}/product-types
Authorization: Bearer {{token}}


### LISTAR TIPO PRODUCTO POR ID
GET {{host}}/{{prefix}}/product-types/83edf977-8cc2-49b1-a47b-59b58cdc0e12
Authorization: Bearer {{token}}


### ACTUALIZAR TIPO PRODUCTO (ADMIN/VENDOR)
PATCH {{host}}/{{prefix}}/product-types/83edf977-8cc2-49b1-a47b-59b58cdc0e12
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Tornillos, Clavos y Fijación",
  "description": "Productos de ferretería"
}

### ELIMINAR
DELETE {{host}}/{{prefix}}/product-types/83edf977-8cc2-49b1-a47b-59b58cdc0e12
Authorization: Bearer {{token}}
